# Generated by Django 4.2.3 on 2023-07-29 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_answerlike_questionlike_questiontags_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_dislike', to='questions.answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dislike_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
